//
//  ALCurrencyCodes.h
//  ALCurrencyLibrary
//
//  Created by Andrea Mario Lufino on 13/11/13.
//  Copyright (c) 2013 Andrea Mario Lufino. All rights reserved.
//


static NSString const * ALC_AED = @"AED"; // Dirham - United Arab Emirates
static NSString const * ALC_AFN = @"AFN"; // Afghani - Afghanistan
static NSString const * ALC_ALL = @"ALL"; // Lek - Albania
static NSString const * ALC_AMD = @"AMD"; // Dram - Armenia
static NSString const * ALC_ANG = @"ANG"; // Netherlands Antillean guilder
static NSString const * ALC_AOA = @"AOA"; // Kwaza - Angola
static NSString const * ALC_ARS = @"ARS"; // Pesos - Argentina
static NSString const * ALC_AUD = @"AUD"; // Australian dollars
static NSString const * ALC_AWG = @"AWG"; // Aruban guilder - Aruba
static NSString const * ALC_AZN = @"AZN"; // Manat - Azerbaigian
static NSString const * ALC_BAM = @"BAM"; // Mark - Bosnia and Erzegovina
static NSString const * ALC_BBD = @"BBD"; // Barbados dollar - Barbados
static NSString const * ALC_BDT = @"BDT"; // Taka - Bangladesh
static NSString const * ALC_BGN = @"BGN"; // Bulgarian Lev - Bulgaria
static NSString const * ALC_BHD = @"BHD"; // Bahraini dinar - Barhain
static NSString const * ALC_BIF = @"BIF"; // Burundian franc - Burundi
static NSString const * ALC_BMD = @"BMD"; // Bermudian dollar - Bermuda
static NSString const * ALC_BND = @"BND"; // Brunei dollar - Brunei
static NSString const * ALC_BOB = @"BOB"; // Boliviano - Bolivia
static NSString const * ALC_BRL = @"BRL"; // Brazilian Real - Brazil
static NSString const * ALC_BSD = @"BSD"; // Bahamas dollar - Bahamas
static NSString const * ALC_BTN = @"BTN"; // Ngultrum - Bhutan
static NSString const * ALC_BWP = @"BWP"; // Pula - Botswana
static NSString const * ALC_BYR = @"BYR"; // Ruble - Bielorussian
static NSString const * ALC_BZD = @"BZD"; // Belize dollar - Belize
static NSString const * ALC_CAD = @"CAD"; // Canadian dollar - Canada
static NSString const * ALC_CDF = @"CDF"; // Congolese franc - Democratic Republic Of Congo
static NSString const * ALC_CHF = @"CHF"; // Swiss franc - Switzerland
static NSString const * ALC_CLP = @"CLP"; // Pesos - Chile
static NSString const * ALC_CNY = @"CNY"; // Yuan - China
static NSString const * ALC_COP = @"COP"; // Pesos - Colombia
static NSString const * ALC_CRC = @"CRC"; // Colòn - Costa Rica
static NSString const * ALC_CUC = @"CUC"; // Pesos - Cuban (one of the two Cuban currencies)
static NSString const * ALC_CUP = @"CUP"; // Pesos - Cuban (the second Cuban currency)
static NSString const * ALC_CVE = @"CVE"; // Escudo - Capo Verde
static NSString const * ALC_CZK = @"CZK"; // Czech koruna - Czech
static NSString const * ALC_DJF = @"DJF"; // Djiboutian franc
static NSString const * ALC_DKK = @"DKK"; // Danish krone
static NSString const * ALC_DOP = @"DOP"; // Pesos - Dominican Republic
static NSString const * ALC_DZD = @"DZD"; // Algerian dinar - Algeria
static NSString const * ALC_EGP = @"EGP"; // Egyptian pound - Egypt
static NSString const * ALC_ERN = @"ERN"; // Eritrean nafka - Eritrea
static NSString const * ALC_ETB = @"ETB"; // Ethiopian birr - Ethiopia
static NSString const * ALC_EUR = @"EUR"; // Euro - Europe
static NSString const * ALC_FJD = @"FJD"; // Fiji dollar - Fiji
static NSString const * ALC_FKP = @"FKP"; // Falkland Islands pound - Falkland Islands
static NSString const * ALC_GBP = @"GBP"; // United Kingdom
static NSString const * ALC_GEL = @"GEL"; // Georgia
static NSString const * ALC_GHS = @"GHS"; // Ghana
static NSString const * ALC_GIP = @"GIP"; // Gibilterra pound
static NSString const * ALC_GMD = @"GMD"; // Dalasi - Gambia
static NSString const * ALC_GNF = @"GNF"; // Franc - Guinea
static NSString const * ALC_GTQ = @"GTQ"; // Quetzal - Guatemala
// DEPRECATED
static NSString const * ALC_GWP = @"GWP"; // Pesos - Guinea
static NSString const * ALC_GYD = @"GYD"; // Dollar - Guyana
static NSString const * ALC_HKD = @"HKD"; // Dollar - Hong Kong
static NSString const * ALC_HNL = @"HNL"; // Lempira - Honduras
static NSString const * ALC_HRK = @"HRK"; // Kuna - Croatia
static NSString const * ALC_HTG = @"HTG"; // Gourde - Haiti
static NSString const * ALC_HUF = @"HUF"; // Forint - Hungary
static NSString const * ALC_IDR = @"IDR"; // Rupiah - Indonesia
static NSString const * ALC_ILS = @"ILS"; // Shekel - Israel
static NSString const * ALC_INR = @"INR"; // Rupiah - India
static NSString const * ALC_IQD = @"IQD"; // Dinar - Iraq
static NSString const * ALC_IRR = @"IRR"; // Rial - Iran
static NSString const * ALC_ISK = @"ISK"; // Krona - Iceland
static NSString const * ALC_JMD = @"JMD"; // Dollar - Jamaica
static NSString const * ALC_JOD = @"JOD"; // Dinar - Giordania
static NSString const * ALC_JPY = @"JPY"; // Yen - Japan
static NSString const * ALC_KES = @"KES"; // Shilling - Kenya
static NSString const * ALC_KGS = @"KGS"; // Som - Kirghizistan
static NSString const * ALC_KHR = @"KHR"; // Riel - Cambogia
static NSString const * ALC_KMF = @"KMF"; // Franc - Comore
static NSString const * ALC_KPW = @"KPW"; // Won - North Korea
static NSString const * ALC_KRW = @"KRW"; // Won - South Korea
static NSString const * ALC_KWD = @"KWD"; // Dinar - Kwait
static NSString const * ALC_KYD = @"KYD"; // Dollar - Cayman
static NSString const * ALC_KZT = @"KZT"; // Tenge - Kazakistan
static NSString const * ALC_LAK = @"LAK"; // Kip - Laos
static NSString const * ALC_LBP = @"LBP"; // Pounds - Liban
static NSString const * ALC_LKR = @"LKR"; // Rupiah - Sri Lanka
static NSString const * ALC_LRD = @"LRD"; // Dollar - Liberia
static NSString const * ALC_LSL = @"LSL"; // Loti - Lesotho
static NSString const * ALC_LTL = @"LTL"; // Lita- Lithuania
static NSString const * ALC_LVL = @"LVL"; // Lats - Latvia
static NSString const * ALC_LYD = @"LYD"; // Dinar - Lybia
static NSString const * ALC_MAD = @"MAD"; // Dirham - Marocco
static NSString const * ALC_MDL = @"MDL"; // Leu - Moldavia
static NSString const * ALC_MGA = @"MGA"; // Ariary - Madagascar
static NSString const * ALC_MKD = @"MKD"; // Dinar - Macedonia
static NSString const * ALC_MMK = @"MMK"; // Kyat - Myanmar
static NSString const * ALC_MNT = @"MNT"; // Tugrik - Mongolia
static NSString const * ALC_MOP = @"MOP"; // Pataca - Macao
static NSString const * ALC_MRO = @"MRO"; // Ouguiya - Mauritania
static NSString const * ALC_MUR = @"MUR"; // Rupiah - Mauritias
static NSString const * ALC_MVR = @"MVR"; // Rufiyaa - Maldive
static NSString const * ALC_MWK = @"MWK"; // Kwacha - Malawi
static NSString const * ALC_MXN = @"MXN"; // Pesos - Mexico
static NSString const * ALC_MYR = @"MYR"; // Ringgit - Malesia
static NSString const * ALC_MZE = @"MZE"; // _______________________________ //
static NSString const * ALC_MZN = @"MZN"; // Metical - Mozambico
static NSString const * ALC_NAD = @"NAD"; // Dollar - Namibia
static NSString const * ALC_NGN = @"NGN"; // Naira - Nigeria
static NSString const * ALC_NIO = @"NIO"; // Cordoba - Nicaragua
static NSString const * ALC_NOK = @"NOK"; // Krone - Norway
static NSString const * ALC_NPR = @"NPR"; // Rupiah - Nepal
static NSString const * ALC_NZD = @"NZD"; // Dollar - New Zealand
static NSString const * ALC_OMR = @"OMR"; // Rial - Oman
static NSString const * ALC_PAB = @"PAB"; // Balboa - Panama
static NSString const * ALC_PEN = @"PEN"; // Nuevo sol - Perù
static NSString const * ALC_PGK = @"PGK"; // Kina - Papua New Guinea
static NSString const * ALC_PHP = @"PHP"; // Pesos - Philippines
static NSString const * ALC_PKR = @"PKR"; // Rupiah - Pakistan
static NSString const * ALC_PLN = @"PLN"; // Złoty - Poland
static NSString const * ALC_PYG = @"PYG"; // Guarani - Paraguay
static NSString const * ALC_QAR = @"QAR"; // Rial - Qatar
static NSString const * ALC_RON = @"RON"; // New Leu - Romania
static NSString const * ALC_RSD = @"RSD"; // Dinar - Serbia
static NSString const * ALC_RUB = @"RUB"; // Rublo - Russia
static NSString const * ALC_RWF = @"RWF"; // Franc - Rwanda
static NSString const * ALC_SAR = @"SAR"; // Riyal - Saudi Arabia
static NSString const * ALC_SBD = @"SBD"; // Dollar - Salomon islands
static NSString const * ALC_SCL = @"SCL"; // Rupiah - Seychelles
static NSString const * ALC_SDG = @"SDG"; // Pounds - Sudan
static NSString const * ALC_SEK = @"SEK"; // Krone - Sweeden
static NSString const * ALC_SGD = @"SGD"; // Dollar - Singapore
static NSString const * ALC_SHP = @"SHP"; // Pound - Sant'elena
static NSString const * ALC_SKK = @"SKK"; // Krone - Slovakia
static NSString const * ALC_SLL = @"SLL"; // Lion - Sierra Leone
static NSString const * ALC_SOS = @"SOS"; // Shilling - Somalia
static NSString const * ALC_SRD = @"SRD"; // Dollar - Suriname
static NSString const * ALC_SSP = @"SSP"; // Pound - South Sudan
static NSString const * ALC_STD = @"STD"; // Dobra - Sao Tomè
// DEPRECATED
static NSString const * ALC_SVC = @"SVC"; // Colon - Salvador
static NSString const * ALC_SYP = @"SYP"; // Pound - Syria
static NSString const * ALC_SZL = @"SZL"; // Lilangeni - Swaziland
static NSString const * ALC_THB = @"THB"; // Baht - Thailandia
static NSString const * ALC_TJS = @"TJS"; // Somoni tagiko - Tagikistan
static NSString const * ALC_TMT = @"TMT"; // Manat - Turkmenistan
static NSString const * ALC_TND = @"TND"; // Dinar - Tunisia
static NSString const * ALC_TOP = @"TOP"; // Paʻanga - Tonga
static NSString const * ALC_TRY = @"TRY"; // Pound - Turkey
static NSString const * ALC_TTD = @"TTD"; // Trinidad & Tobago
static NSString const * ALC_TWD = @"TWD"; // Dollar - Taiwan
static NSString const * ALC_TZS = @"TZS"; // Shilling - Tanzania
static NSString const * ALC_UAH = @"UAH"; // Grivnia - Ukrain
static NSString const * ALC_UGX = @"UGX"; // Shilling - Uganda
static NSString const * ALC_USD = @"USD"; // Dollar - United States
static NSString const * ALC_UYU = @"UYU"; // Pesos - Uruguay
static NSString const * ALC_UZS = @"UZS"; // Som - Uzbekistan
static NSString const * ALC_VEF = @"VEF"; // Bolivar Fuerte - Venezuela
static NSString const * ALC_VND = @"VND"; // Đồng - Vietnam
static NSString const * ALC_VUV = @"VUV"; // Vatu - Vanuatu
static NSString const * ALC_WST = @"WST"; // Tala - Samoa
static NSString const * ALC_XAF = @"XAF"; // Franc CFA BEAC - Camerun, Middle Africa Republic, Congo Republic, Ciad, Equatorial Guinea, Gabon
static NSString const * ALC_XCD = @"XCD"; // West Caribbean Dollar - Anguilla, Antigua e Barbuda, Dominica, Grenada, Montserrat, Saint Kitts e Nevis, Saint Vincent e Grenadine, Santa Lucia
static NSString const * ALC_XOF = @"XOF"; // Franc CFA BCEAO - Benin, Burkina Faso, Costa d'Avorio, Guinea-Bissau, Mali, Niger, Senegal, Togo
static NSString const * ALC_XPF = @"XPF"; // Franc CFP - French Polinesia, New Caledonia, Wallis e Futuna
static NSString const * ALC_YER = @"YER"; // Rial - Yemen
static NSString const * ALC_ZAR = @"ZAR"; // Rand - South Africa
static NSString const * ALC_ZMW = @"ZMW"; // Kwacha - Zambia
